### ISSUE TITLE
Update to use new baldrick framework

### ISSUE THREAD

**Issue by drdavella** [spacetelescope/stsci-bot-old#8]
See [here](https://github.com/astrofrog/baldrick).

**Comment by pllim** [comment]
@drdavella , the code base has diverged too much. I am thinking to start this afresh from `astropy/astropy-bot` `master`. Is there any particular customization you want to keep before I do that? To do a merge might have too much conflict. So I am thinking of a completely new `master` branch here that is fresh. But I will backup the current `master` to `old` or something first.

**Comment by pllim** [comment]
**OR** instead of this being a fork of `astropy/astropy-bot`, we can completely detach from it by writing our own plugin into `baldrick` directly.

**Comment by drdavella** [comment]
I think that's fine. The only major divergence that I can think of is that @mcara asked me to add an option to disable the milestone check (see #11). Other than that, I think a fresh clone would be okay.
